/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visual;


import controladores.controladorTriangulo;
import java.awt.*;
import javax.swing.JPanel;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JTextField;

import modelo.*;
//import com.mapbox.api.isochrone;

/**
 *
 * @author David B
 */
public class Interfaz1 extends javax.swing.JFrame {
    
    private controladorTriangulo controlador;

    /**
     * Creates new form Interfaz
     */
    public Interfaz1() {
        initComponents();
        setLocationRelativeTo(null);
        ConfirmarSalida.setLocationRelativeTo(null);
        ocultarPanelesExceptoEste(Inicio);
        controlador = new controladorTriangulo();
    }
    
    /**
     * Oculta los paneles y deja solo 1 visible
     * @param panel panel a dejar visible
     * @param limpiarPanel accion de limpiar el resto de paneles
     */
    private void ocultarPanelesExceptoEste(JPanel panel, boolean ... limpiarPanel){
        boolean flagLimpiarPanel = (limpiarPanel.length >= 1) ? limpiarPanel[0] : false;
        
        for(Component componente : Paneles.getComponents()) 
            if(componente instanceof JPanel)
                componente.setVisible(false);
        
        if(flagLimpiarPanel) limpiarVentana(panel);
        
        panel.setVisible(true);
    }
    
    /**
     * Limpiar ventanas
     * @param panel Panel a limpiar
     */
    private void limpiarVentana(JPanel panel){
        for(Component componente : panel.getComponents()){   
            if(componente instanceof JTextField){
                JTextField comp = (JTextField) componente;
                comp.setText("");
            }
            else if (componente instanceof JComboBox){
                JComboBox comp = (JComboBox) componente;
                comp.setSelectedIndex(0);
            }
            else if(componente instanceof JFormattedTextField){
                JFormattedTextField comp = (JFormattedTextField) componente;
                comp.setText("");
            }
        }
    }
    
    /**
     * Cerrar Programa
     * @return 
     */
    private int cerrarPrograma(){
        ConfirmarSalida.setVisible(true);
        Paneles.setVisible(false);
        return 0;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ConfirmarSalida = new javax.swing.JDialog();
        botonAceptar_ConfirmarSalida = new javax.swing.JButton();
        botonCancelar_ConfirmarSalida = new javax.swing.JButton();
        textConfirmarSalida_ConfirmarSalida = new javax.swing.JLabel();
        MensajeError_NuevoSismo = new javax.swing.JFrame();
        Paneles = new javax.swing.JLayeredPane();
        Inicio = new javax.swing.JPanel();
        triangulos_Pascal = new javax.swing.JButton();
        quincunce_boton = new javax.swing.JButton();
        textTitulo_Inicio = new javax.swing.JLabel();
        botonSalir_Inicio = new javax.swing.JButton();
        detalle_Inicio = new javax.swing.JTextArea();
        detalle_Inicio1 = new javax.swing.JTextArea();
        Ventana_Triangulos = new javax.swing.JPanel();
        textTitulo_VentanaIntermedia = new javax.swing.JLabel();
        botonRegresar_VentanaIntermedia = new javax.swing.JButton();
        botonSalir_NuevoSismo_Ubicacion1 = new javax.swing.JButton();
        botonDiagonales = new javax.swing.JButton();
        botonPar_Impar = new javax.swing.JButton();
        botonSuma_Horizontal = new javax.swing.JButton();
        botonSimetria = new javax.swing.JButton();
        botonFibronacci = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        mostrarTriangulo_Panel = new javax.swing.JPanel();
        valorNum_Filas = new javax.swing.JTextField();
        botonIr_Quincunce = new javax.swing.JButton();
        Quincunce = new javax.swing.JPanel();
        textTitulo_RegistroSismos = new javax.swing.JLabel();
        botonAceptar_RegistroSismos = new javax.swing.JButton();
        botonSalir_RegistroSismos = new javax.swing.JButton();

        ConfirmarSalida.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        ConfirmarSalida.setTitle("Confirmación de Salida");
        ConfirmarSalida.setAlwaysOnTop(true);
        ConfirmarSalida.setMinimumSize(new java.awt.Dimension(306, 157));
        ConfirmarSalida.setSize(new java.awt.Dimension(306, 157));
        ConfirmarSalida.setType(java.awt.Window.Type.POPUP);

        botonAceptar_ConfirmarSalida.setText("Aceptar");
        botonAceptar_ConfirmarSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptar_ConfirmarSalidaActionPerformed(evt);
            }
        });

        botonCancelar_ConfirmarSalida.setText("Cancelar");
        botonCancelar_ConfirmarSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelar_ConfirmarSalidaActionPerformed(evt);
            }
        });

        textConfirmarSalida_ConfirmarSalida.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textConfirmarSalida_ConfirmarSalida.setText("Desea terminar el programa?");

        javax.swing.GroupLayout ConfirmarSalidaLayout = new javax.swing.GroupLayout(ConfirmarSalida.getContentPane());
        ConfirmarSalida.getContentPane().setLayout(ConfirmarSalidaLayout);
        ConfirmarSalidaLayout.setHorizontalGroup(
            ConfirmarSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConfirmarSalidaLayout.createSequentialGroup()
                .addGroup(ConfirmarSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ConfirmarSalidaLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(botonAceptar_ConfirmarSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(botonCancelar_ConfirmarSalida))
                    .addGroup(ConfirmarSalidaLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(textConfirmarSalida_ConfirmarSalida)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        ConfirmarSalidaLayout.setVerticalGroup(
            ConfirmarSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ConfirmarSalidaLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(textConfirmarSalida_ConfirmarSalida)
                .addGap(18, 18, 18)
                .addGroup(ConfirmarSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAceptar_ConfirmarSalida)
                    .addComponent(botonCancelar_ConfirmarSalida))
                .addGap(51, 51, 51))
        );

        javax.swing.GroupLayout MensajeError_NuevoSismoLayout = new javax.swing.GroupLayout(MensajeError_NuevoSismo.getContentPane());
        MensajeError_NuevoSismo.getContentPane().setLayout(MensajeError_NuevoSismoLayout);
        MensajeError_NuevoSismoLayout.setHorizontalGroup(
            MensajeError_NuevoSismoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        MensajeError_NuevoSismoLayout.setVerticalGroup(
            MensajeError_NuevoSismoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Sismos");
        setBackground(new java.awt.Color(0, 0, 0));
        setMinimumSize(new java.awt.Dimension(750, 380));
        setName("Base"); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Paneles.setBackground(new java.awt.Color(0, 0, 0));
        Paneles.setMaximumSize(new java.awt.Dimension(750, 380));
        Paneles.setMinimumSize(new java.awt.Dimension(750, 380));
        Paneles.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Inicio.setBackground(new java.awt.Color(153, 255, 102));
        Inicio.setMaximumSize(new java.awt.Dimension(750, 510));
        Inicio.setMinimumSize(new java.awt.Dimension(750, 510));
        Inicio.setPreferredSize(new java.awt.Dimension(750, 510));

        triangulos_Pascal.setBackground(new java.awt.Color(0, 153, 102));
        triangulos_Pascal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        triangulos_Pascal.setForeground(new java.awt.Color(255, 255, 255));
        triangulos_Pascal.setText("Triángulo de Pascal");
        triangulos_Pascal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        triangulos_Pascal.setBorderPainted(false);
        triangulos_Pascal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        triangulos_Pascal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                triangulos_PascalActionPerformed(evt);
            }
        });

        quincunce_boton.setBackground(new java.awt.Color(29, 53, 87));
        quincunce_boton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        quincunce_boton.setForeground(new java.awt.Color(255, 255, 255));
        quincunce_boton.setText("Quincunce");
        quincunce_boton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        quincunce_boton.setBorderPainted(false);
        quincunce_boton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        quincunce_boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quincunce_botonActionPerformed(evt);
            }
        });

        textTitulo_Inicio.setBackground(new java.awt.Color(238, 108, 77));
        textTitulo_Inicio.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        textTitulo_Inicio.setForeground(new java.awt.Color(29, 53, 87));
        textTitulo_Inicio.setText("Inicio  ");

        botonSalir_Inicio.setBackground(new java.awt.Color(255, 0, 0));
        botonSalir_Inicio.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        botonSalir_Inicio.setForeground(new java.awt.Color(255, 255, 255));
        botonSalir_Inicio.setText("Salir");
        botonSalir_Inicio.setBorderPainted(false);
        botonSalir_Inicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonSalir_Inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalir_InicioActionPerformed(evt);
            }
        });

        detalle_Inicio.setEditable(false);
        detalle_Inicio.setBackground(new java.awt.Color(153, 255, 102));
        detalle_Inicio.setColumns(20);
        detalle_Inicio.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        detalle_Inicio.setForeground(new java.awt.Color(29, 53, 87));
        detalle_Inicio.setRows(5);
        detalle_Inicio.setText("Esta es una asombrosa máquina creada por Sir \nFrancis Galton y es igual a un triángulo de Pascal\npero con palos.\nSe pueden crear experiencias aleatorias.");
        detalle_Inicio.setAutoscrolls(false);
        detalle_Inicio.setBorder(null);
        detalle_Inicio.setCaretColor(new java.awt.Color(61, 90, 128));
        detalle_Inicio.setFocusable(false);

        detalle_Inicio1.setEditable(false);
        detalle_Inicio1.setBackground(new java.awt.Color(153, 255, 102));
        detalle_Inicio1.setColumns(20);
        detalle_Inicio1.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        detalle_Inicio1.setForeground(new java.awt.Color(29, 53, 87));
        detalle_Inicio1.setRows(5);
        detalle_Inicio1.setText("El triángulo de Pascal es un triángulo de números\nenteros, infinito y simétrico.  \nSe empieza con la primer fila, y en las siguientes\nse van colocando números de forma que cada \nuno de ellos sea la suma de los dos números \nque tiene encima.");
        detalle_Inicio1.setAutoscrolls(false);
        detalle_Inicio1.setBorder(null);
        detalle_Inicio1.setCaretColor(new java.awt.Color(61, 90, 128));
        detalle_Inicio1.setFocusable(false);

        javax.swing.GroupLayout InicioLayout = new javax.swing.GroupLayout(Inicio);
        Inicio.setLayout(InicioLayout);
        InicioLayout.setHorizontalGroup(
            InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InicioLayout.createSequentialGroup()
                .addGroup(InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InicioLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(textTitulo_Inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InicioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(detalle_Inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(triangulos_Pascal, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                    .addComponent(quincunce_boton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(60, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InicioLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(botonSalir_Inicio)
                .addGap(26, 26, 26))
            .addGroup(InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(InicioLayout.createSequentialGroup()
                    .addGap(39, 39, 39)
                    .addComponent(detalle_Inicio1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(342, Short.MAX_VALUE)))
        );
        InicioLayout.setVerticalGroup(
            InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InicioLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(textTitulo_Inicio)
                .addGap(16, 16, 16)
                .addComponent(triangulos_Pascal, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addGroup(InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(quincunce_boton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(detalle_Inicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(botonSalir_Inicio)
                .addContainerGap(70, Short.MAX_VALUE))
            .addGroup(InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(InicioLayout.createSequentialGroup()
                    .addGap(85, 85, 85)
                    .addComponent(detalle_Inicio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(299, Short.MAX_VALUE)))
        );

        Paneles.add(Inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Ventana_Triangulos.setBackground(new java.awt.Color(230, 57, 70));
        Ventana_Triangulos.setMaximumSize(new java.awt.Dimension(750, 510));
        Ventana_Triangulos.setMinimumSize(new java.awt.Dimension(750, 510));

        textTitulo_VentanaIntermedia.setBackground(new java.awt.Color(29, 53, 87));
        textTitulo_VentanaIntermedia.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        textTitulo_VentanaIntermedia.setForeground(new java.awt.Color(241, 250, 238));
        textTitulo_VentanaIntermedia.setText(" Triángulo de Pascal");
        textTitulo_VentanaIntermedia.setOpaque(true);

        botonRegresar_VentanaIntermedia.setText("Regresar");
        botonRegresar_VentanaIntermedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresar_VentanaIntermediaActionPerformed(evt);
            }
        });

        botonSalir_NuevoSismo_Ubicacion1.setText("Salir");
        botonSalir_NuevoSismo_Ubicacion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalir_NuevoSismo_Ubicacion1ActionPerformed(evt);
            }
        });

        botonDiagonales.setBackground(new java.awt.Color(29, 53, 87));
        botonDiagonales.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botonDiagonales.setForeground(new java.awt.Color(255, 255, 255));
        botonDiagonales.setText("Diagonales");
        botonDiagonales.setBorderPainted(false);
        botonDiagonales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDiagonalesActionPerformed(evt);
            }
        });

        botonPar_Impar.setBackground(new java.awt.Color(29, 53, 87));
        botonPar_Impar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botonPar_Impar.setForeground(new java.awt.Color(255, 255, 255));
        botonPar_Impar.setText("Pares e Impares");
        botonPar_Impar.setBorderPainted(false);
        botonPar_Impar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPar_ImparActionPerformed(evt);
            }
        });

        botonSuma_Horizontal.setBackground(new java.awt.Color(29, 53, 87));
        botonSuma_Horizontal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botonSuma_Horizontal.setForeground(new java.awt.Color(255, 255, 255));
        botonSuma_Horizontal.setText("Suma Horizontal");
        botonSuma_Horizontal.setBorderPainted(false);
        botonSuma_Horizontal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSuma_HorizontalActionPerformed(evt);
            }
        });

        botonSimetria.setBackground(new java.awt.Color(29, 53, 87));
        botonSimetria.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botonSimetria.setForeground(new java.awt.Color(255, 255, 255));
        botonSimetria.setText("Simetría");
        botonSimetria.setBorderPainted(false);
        botonSimetria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSimetriaActionPerformed(evt);
            }
        });

        botonFibronacci.setBackground(new java.awt.Color(29, 53, 87));
        botonFibronacci.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botonFibronacci.setForeground(new java.awt.Color(255, 255, 255));
        botonFibronacci.setText("Fibronacci");
        botonFibronacci.setBorderPainted(false);
        botonFibronacci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFibronacciActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ingrese el número de filas para el Triángulo de Pascal: ");

        mostrarTriangulo_Panel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout mostrarTriangulo_PanelLayout = new javax.swing.GroupLayout(mostrarTriangulo_Panel);
        mostrarTriangulo_Panel.setLayout(mostrarTriangulo_PanelLayout);
        mostrarTriangulo_PanelLayout.setHorizontalGroup(
            mostrarTriangulo_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        mostrarTriangulo_PanelLayout.setVerticalGroup(
            mostrarTriangulo_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );

        valorNum_Filas.setText(" ");
        valorNum_Filas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorNum_FilasActionPerformed(evt);
            }
        });

        botonIr_Quincunce.setBackground(new java.awt.Color(29, 53, 87));
        botonIr_Quincunce.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botonIr_Quincunce.setForeground(new java.awt.Color(255, 255, 255));
        botonIr_Quincunce.setText("Ir a Quincunce");
        botonIr_Quincunce.setBorderPainted(false);
        botonIr_Quincunce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIr_QuincunceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Ventana_TriangulosLayout = new javax.swing.GroupLayout(Ventana_Triangulos);
        Ventana_Triangulos.setLayout(Ventana_TriangulosLayout);
        Ventana_TriangulosLayout.setHorizontalGroup(
            Ventana_TriangulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Ventana_TriangulosLayout.createSequentialGroup()
                .addComponent(textTitulo_VentanaIntermedia, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(Ventana_TriangulosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Ventana_TriangulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mostrarTriangulo_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(Ventana_TriangulosLayout.createSequentialGroup()
                        .addGroup(Ventana_TriangulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Ventana_TriangulosLayout.createSequentialGroup()
                                .addComponent(botonDiagonales)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonPar_Impar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonSuma_Horizontal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonSimetria)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botonFibronacci)
                                .addGap(23, 23, 23))
                            .addGroup(Ventana_TriangulosLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(valorNum_Filas, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(Ventana_TriangulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(Ventana_TriangulosLayout.createSequentialGroup()
                                .addComponent(botonRegresar_VentanaIntermedia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonSalir_NuevoSismo_Ubicacion1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(botonIr_Quincunce, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        Ventana_TriangulosLayout.setVerticalGroup(
            Ventana_TriangulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Ventana_TriangulosLayout.createSequentialGroup()
                .addComponent(textTitulo_VentanaIntermedia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mostrarTriangulo_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Ventana_TriangulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonDiagonales)
                    .addComponent(botonRegresar_VentanaIntermedia)
                    .addComponent(botonSalir_NuevoSismo_Ubicacion1)
                    .addComponent(botonPar_Impar)
                    .addComponent(botonSuma_Horizontal)
                    .addComponent(botonSimetria)
                    .addComponent(botonFibronacci))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Ventana_TriangulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Ventana_TriangulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(valorNum_Filas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(botonIr_Quincunce))
                .addGap(46, 46, 46))
        );

        Paneles.add(Ventana_Triangulos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Quincunce.setBackground(new java.awt.Color(29, 53, 87));
        Quincunce.setMaximumSize(new java.awt.Dimension(750, 510));
        Quincunce.setMinimumSize(new java.awt.Dimension(750, 510));
        Quincunce.setName(""); // NOI18N
        Quincunce.setPreferredSize(new java.awt.Dimension(750, 510));
        Quincunce.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textTitulo_RegistroSismos.setBackground(new java.awt.Color(230, 57, 70));
        textTitulo_RegistroSismos.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        textTitulo_RegistroSismos.setForeground(new java.awt.Color(241, 250, 238));
        textTitulo_RegistroSismos.setText("Quincunce");
        textTitulo_RegistroSismos.setOpaque(true);
        Quincunce.add(textTitulo_RegistroSismos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, -1));

        botonAceptar_RegistroSismos.setText("Regresar");
        botonAceptar_RegistroSismos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptar_RegistroSismosActionPerformed(evt);
            }
        });
        Quincunce.add(botonAceptar_RegistroSismos, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 330, -1, -1));

        botonSalir_RegistroSismos.setText("Salir");
        botonSalir_RegistroSismos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalir_RegistroSismosActionPerformed(evt);
            }
        });
        Quincunce.add(botonSalir_RegistroSismos, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 330, 71, -1));

        Paneles.add(Quincunce, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(Paneles, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void triangulos_PascalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_triangulos_PascalActionPerformed
        ocultarPanelesExceptoEste(Ventana_Triangulos,true);
    }//GEN-LAST:event_triangulos_PascalActionPerformed

    private void quincunce_botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quincunce_botonActionPerformed
        ocultarPanelesExceptoEste(Quincunce);
    }//GEN-LAST:event_quincunce_botonActionPerformed

    private void botonSalir_InicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalir_InicioActionPerformed
        cerrarPrograma();
    }//GEN-LAST:event_botonSalir_InicioActionPerformed

    private void botonAceptar_ConfirmarSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptar_ConfirmarSalidaActionPerformed
        System.exit(0);
    }//GEN-LAST:event_botonAceptar_ConfirmarSalidaActionPerformed

    private void botonCancelar_ConfirmarSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelar_ConfirmarSalidaActionPerformed
        ConfirmarSalida.setVisible(false);
        Paneles.setVisible(true);
    }//GEN-LAST:event_botonCancelar_ConfirmarSalidaActionPerformed
    
    private void botonAceptar_RegistroSismosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptar_RegistroSismosActionPerformed
        ocultarPanelesExceptoEste(Inicio);
    }//GEN-LAST:event_botonAceptar_RegistroSismosActionPerformed

    private void botonSalir_RegistroSismosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalir_RegistroSismosActionPerformed
        cerrarPrograma();
    }//GEN-LAST:event_botonSalir_RegistroSismosActionPerformed

    private void botonRegresar_VentanaIntermediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresar_VentanaIntermediaActionPerformed
        ocultarPanelesExceptoEste(Inicio);
    }//GEN-LAST:event_botonRegresar_VentanaIntermediaActionPerformed

    private void botonSalir_NuevoSismo_Ubicacion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalir_NuevoSismo_Ubicacion1ActionPerformed
        cerrarPrograma();
    }//GEN-LAST:event_botonSalir_NuevoSismo_Ubicacion1ActionPerformed

    private void botonDiagonalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDiagonalesActionPerformed
        mostrarTriangulo_Panel.removeAll();
        int dato = Integer.parseInt(valorNum_Filas.getText().trim());
        Diagonal diagonales = new Diagonal();
        int[][] matriz = modelo.TrianguloPascal.crearMatriz(dato);
        diagonales.triangulo(mostrarTriangulo_Panel.getGraphics(), 285, 30, 30, 30, dato, matriz);
    }//GEN-LAST:event_botonDiagonalesActionPerformed

    private void botonPar_ImparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPar_ImparActionPerformed
        mostrarTriangulo_Panel.removeAll();
        int dato = Integer.parseInt(valorNum_Filas.getText().trim());
        ParImpar paresImpares = new ParImpar();
        int[][] matriz = modelo.TrianguloPascal.crearMatriz(dato);
        paresImpares.triangulo(mostrarTriangulo_Panel.getGraphics(), 285, 30, 30, 30, dato, matriz);
    }//GEN-LAST:event_botonPar_ImparActionPerformed

    private void botonSuma_HorizontalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSuma_HorizontalActionPerformed
        mostrarTriangulo_Panel.removeAll();
        int dato = Integer.parseInt(valorNum_Filas.getText().trim());
        SumaHorizontal sumandoHorizontal = new SumaHorizontal();
        int[][] matriz = modelo.TrianguloPascal.crearMatriz(dato);
        sumandoHorizontal.triangulo(mostrarTriangulo_Panel.getGraphics(), 285, 30, 30, 30, dato, matriz);                                              
    }//GEN-LAST:event_botonSuma_HorizontalActionPerformed

    private void botonSimetriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSimetriaActionPerformed
        mostrarTriangulo_Panel.removeAll();
        int dato = Integer.parseInt(valorNum_Filas.getText().trim());
        Simetria simeTriangulo = new Simetria();
        int[][] matriz = modelo.TrianguloPascal.crearMatriz(dato);
        simeTriangulo.triangulo(mostrarTriangulo_Panel.getGraphics(), 285, 30, 30, 30, dato, matriz); 
    }//GEN-LAST:event_botonSimetriaActionPerformed

    private void botonFibronacciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFibronacciActionPerformed
        mostrarTriangulo_Panel.removeAll();
        int dato = Integer.parseInt(valorNum_Filas.getText().trim());
        Fibronacci fibroTriangulo = new Fibronacci();
        int[][] matriz = modelo.TrianguloPascal.crearMatriz(dato);
        fibroTriangulo.triangulo(mostrarTriangulo_Panel.getGraphics(), 285, 30, 30, 30, dato, matriz); 
    }//GEN-LAST:event_botonFibronacciActionPerformed

    private void valorNum_FilasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorNum_FilasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorNum_FilasActionPerformed

    private void botonIr_QuincunceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIr_QuincunceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonIr_QuincunceActionPerformed
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz1().setVisible(true);
            }
        });
        
        
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog ConfirmarSalida;
    private javax.swing.JPanel Inicio;
    private javax.swing.JFrame MensajeError_NuevoSismo;
    private javax.swing.JLayeredPane Paneles;
    private javax.swing.JPanel Quincunce;
    private javax.swing.JPanel Ventana_Triangulos;
    private javax.swing.JButton botonAceptar_ConfirmarSalida;
    private javax.swing.JButton botonAceptar_RegistroSismos;
    private javax.swing.JButton botonCancelar_ConfirmarSalida;
    private javax.swing.JButton botonDiagonales;
    private javax.swing.JButton botonFibronacci;
    private javax.swing.JButton botonIr_Quincunce;
    private javax.swing.JButton botonPar_Impar;
    private javax.swing.JButton botonRegresar_VentanaIntermedia;
    private javax.swing.JButton botonSalir_Inicio;
    private javax.swing.JButton botonSalir_NuevoSismo_Ubicacion1;
    private javax.swing.JButton botonSalir_RegistroSismos;
    private javax.swing.JButton botonSimetria;
    private javax.swing.JButton botonSuma_Horizontal;
    private javax.swing.JTextArea detalle_Inicio;
    private javax.swing.JTextArea detalle_Inicio1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel mostrarTriangulo_Panel;
    private javax.swing.JButton quincunce_boton;
    private javax.swing.JLabel textConfirmarSalida_ConfirmarSalida;
    private javax.swing.JLabel textTitulo_Inicio;
    private javax.swing.JLabel textTitulo_RegistroSismos;
    private javax.swing.JLabel textTitulo_VentanaIntermedia;
    private javax.swing.JButton triangulos_Pascal;
    private javax.swing.JTextField valorNum_Filas;
    // End of variables declaration//GEN-END:variables



}

